{% set name = "types-lxml" %}
{% set version = "2024.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: f584856fe84cc05f7f5fd0da00308101f75a94a1d4e48ca6e6ab9eade0052d49
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - types-beautifulsoup4
    - typing-extensions

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/lxml-stubs/__init__.pyi                 # [unix]
    - if not exist %SP_DIR%\\lxml-stubs\\__init__.pyi exit 1  # [win]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for lxml
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zwelz3
