{% set name = "types-lxml" %}
{% set version = "2024.11.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: 0cdb4d943cb104e019b7273fd24af72a0826d0043b3e5100b672c3bb99028e00
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - types-beautifulsoup4
    - typing-extensions
    - cssselect

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/lxml-stubs/__init__.pyi                 # [unix]
    - if not exist %SP_DIR%\\lxml-stubs\\__init__.pyi exit 1  # [win]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for lxml
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zwelz3
